services:
  web:
    build: .
    ports:
      - "8009:8000"
    volumes:
      - ./instance:/app/instance
      - ./app/static/uploads:/app/app/static/uploads
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=sqlite:////app/instance/app.db
      - FLASK_APP=run.py
      - FLASK_DEBUG=0
    restart: unless-stopped
